apiVersion: v1
entries:
  calert:
  - apiVersion: v2
    appVersion: v2.3.0
    created: "2026-01-08T11:31:42.348920942Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: 8ba42b3574a3dfd3264bc27523f1be2336974ece838dc453490b38d9f2406317
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://mr-karan.github.io/calert/charts/calert-v2.3.0.tgz
    version: v2.3.0
  - apiVersion: v2
    appVersion: v2.2.0
    created: "2025-09-09T11:26:41.961710833Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: dc1cbb842968b2d0706e32df10ae1b612761566ae0d9d8dfe1fb53008e7daa30
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://mr-karan.github.io/calert/charts/calert-v2.2.0.tgz
    version: v2.2.0
  - apiVersion: v2
    appVersion: v2.1.1
    created: "2024-03-13T05:42:45.293528825Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: 6a96514f36127e29a9249c6302093170c71abc8096967b573fd8475ee744f074
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://mr-karan.github.io/calert/charts/calert-v2.1.1.tgz
    version: v2.1.1
  - apiVersion: v2
    appVersion: v2.1.0
    created: "2024-02-23T05:35:25.725564963Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: e27a5e6b3235ee78a70618b930f2e37492abbe10ab7c9313c3b614ef396160a3
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://mr-karan.github.io/calert/charts/calert-v2.1.0.tgz
    version: v2.1.0
  - apiVersion: v2
    appVersion: v2.0.7
    created: "2023-11-20T10:40:22.768493627Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: f7837a0b0de673366e806f1755f9c86c9fa7e9718affda479ec8ac0224975bb1
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://mr-karan.github.io/calert/charts/calert-v2.0.7.tgz
    version: v2.0.7
  - apiVersion: v2
    appVersion: v0.2.2
    created: "2025-08-12T06:51:11.517324405Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: bfb15b3a057d36908319d00f10fb71be79c02cdbfa421b9479fe99ece037029e
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://mr-karan.github.io/calert/charts/calert-v0.2.2.tgz
    version: v0.2.2
generated: "2026-01-08T11:31:42.348094455Z"
